const mongoose= require('mongoose');

const Schema = mongoose.Schema;

const flightShema= new Schema({
    flightType1:{ type:String, required:false},
    flightType2:{ type:String, required:false},
    flightType3:{ type:String, required:false},
    flightType4:{ type:String, required:false},
    note: {type:String, required:false },
    date1: {type: String, required:false },
    date2: {type: String, required:false },
    date3: {type: String, required:false },
    date4: {type: String, required:false },
    paxnbr1: {type: String, required:false },
    paxnbr2: {type: String, required:false },
    paxnbr3: {type: String, required:false },
    paxnbr4: {type: String, required:false },
    departureTime1: {type: String, required:false },
    departureTime2: {type: String, required:false },
    departureTime3: {type: String, required:false },
    departureTime4: {type: String, required:false },
    originIcao1: {type: String, required:false },
    originIcao2: {type: String, required:false },
    originIcao3: {type: String, required:false },
    originIcao4: {type: String, required:false },
    destinationIcao1: {type: String, required:false },
    destinationIcao2: {type: String, required:false },
    destinationIcao3: {type: String, required:false },
    destinationIcao4: {type: String, required:false },
    arrivalTime1: {type: String, required:false },
    arrivalTime2: {type: String, required:false },
    arrivalTime3: {type: String, required:false },
    arrivalTime4: {type: String, required:false },
    hendlerOrigin: {type: String, required:false },
    hendlerOrigin1: {type: String, required:false },
    hendlerOrigin2: {type: String, required:false },
    hendlerOrigin3: {type: String, required:false },
    hendlerDestination1:{type: String, required:false },
    hendlerDestination2:{type: String, required:false },
    hendlerDestination3:{type: String, required:false },
    hendlerDestination4:{type: String, required:false },
    registration:{ type:String, required:true},
    callsign:{ type:String, required:true},
    msp1:{ type:String, required:true},
    msp2:{ type:String, required:false},
    msp3:{ type:String, required:false},
    msp4:{ type:String, required:false},
    handling:[{ type:String, required:false}],
    doz:[{ type:String, required:false}],
    slot:[{ type:String, required:false}],
    ovf:[{ type:String, required:false}],
    vip:[{ type:String, required:false}],
    noteOps:[{ type:String, required:false}],
    crew:[{ type:String, required:false}],
    selectCapt:{ type:String, required:false},
    airportsData:[{ type:Object, required:false}]
});

module.exports= mongoose.model('Flight', flightShema);